language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.2

script:
  - "bundle exec rake spec"

branches:
  only:
    - master

env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.6.2"

notifications:
  email:
    recipients:
      - feniix@gmail.com
    on_failure: always
    on_success: change


