---
language: ruby
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
branches:
  only:
    - master
matrix:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0"
notifications:
  email:
    recipients:
      - feniix@gmail.com
    on_failure: always
    on_success: change

